/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionOsRouteImport } from './routes/mission-os'
import { Route as IndexRouteImport } from './routes/index'

const MissionOsRoute = MissionOsRouteImport.update({
  id: '/mission-os',
  path: '/mission-os',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mission-os': typeof MissionOsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mission-os': typeof MissionOsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mission-os': typeof MissionOsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mission-os'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mission-os'
  id: '__root__' | '/' | '/mission-os'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MissionOsRoute: typeof MissionOsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mission-os': {
      id: '/mission-os'
      path: '/mission-os'
      fullPath: '/mission-os'
      preLoaderRoute: typeof MissionOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MissionOsRoute: MissionOsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
